import type { Product, Invoice, Customer, User } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@nexusstore.com',
    displayName: 'Admin User',
    role: 'admin',
    photoURL: 'https://i.pravatar.cc/150?u=admin@nexusstore.com',
    isActive: true,
    createdAt: new Date(),
    lastLogin: new Date(),
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Quantum-Flux Laptop',
    description: 'High-performance laptop for professionals and gamers.',
    sku: 'NEX-LAP-001',
    barcode: '1234567890123',
    price: 1499.99,
    cost: 950.0,
    stock: 25,
    minStock: 10,
    category: 'Electronics',
    supplier: 'SynthTech Inc.',
    imageUrl: 'https://picsum.photos/seed/NEX-LAP-001/400/400',
    isActive: true,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-2',
    name: 'Ergo-Flow Mechanical Keyboard',
    description: 'Ergonomic keyboard with customizable RGB lighting.',
    sku: 'NEX-KBD-002',
    barcode: '1234567890124',
    price: 179.99,
    cost: 110.0,
    stock: 8,
    minStock: 15,
    category: 'Accessories',
    supplier: 'PeriGear Ltd.',
    imageUrl: 'https://picsum.photos/seed/NEX-KBD-002/400/400',
    isActive: true,
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-3',
    name: 'Aura-Glow Smart Lamp',
    description: 'Smart lamp with voice control and millions of colors.',
    sku: 'NEX-LMP-003',
    barcode: '1234567890125',
    price: 89.99,
    cost: 55.0,
    stock: 50,
    minStock: 20,
    category: 'Smart Home',
    supplier: 'LumiCore',
    imageUrl: 'https://picsum.photos/seed/NEX-LMP-003/400/400',
    isActive: true,
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-4',
    name: 'Hydro-Pulse Water Bottle',
    description: 'Insulated stainless steel water bottle.',
    sku: 'NEX-BOT-004',
    barcode: '1234567890126',
    price: 29.99,
    cost: 15.0,
    stock: 120,
    minStock: 50,
    category: 'Lifestyle',
    supplier: 'StayHydrated Co.',
    imageUrl: 'https://picsum.photos/seed/NEX-BOT-004/400/400',
    isActive: true,
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-5',
    name: 'Zenith VR Headset',
    description: 'Immersive virtual reality headset for next-gen experiences.',
    sku: 'NEX-VRH-005',
    barcode: '1234567890127',
    price: 499.99,
    cost: 320.0,
    stock: 4,
    minStock: 5,
    category: 'Gaming',
    supplier: 'Visionary Tech',
    imageUrl: 'https://picsum.photos/seed/NEX-VRH-005/400/400',
    isActive: true,
    createdAt: new Date('2023-05-21'),
    updatedAt: new Date(),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Elena Rodriguez',
    email: 'elena.r@example.com',
    phone: '555-0101',
    address: '123 Innovation Drive, Tech City',
    taxId: 'ID123456789',
    creditLimit: 5000,
    currentBalance: 2149.98,
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-2',
    name: 'Ben Carter',
    email: 'ben.c@example.com',
    phone: '555-0102',
    address: '456 Market Street, Commerce Town',
    taxId: 'ID987654321',
    creditLimit: 2000,
    currentBalance: 0,
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-3',
    name: 'Aisha Khan',
    email: 'aisha.k@example.com',
    phone: '555-0103',
    address: '789 Silicon Ave, Futureville',
    taxId: 'ID564738291',
    creditLimit: 10000,
    currentBalance: 499.99,
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date(),
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'FAC-2024-0001',
    customerId: 'cust-1',
    customerName: 'Elena Rodriguez',
    items: [
      {
        productId: 'prod-1',
        productName: 'Quantum-Flux Laptop',
        quantity: 1,
        unitPrice: 1499.99,
        subtotal: 1499.99,
      },
    ],
    subtotal: 1499.99,
    tax: 285.0,
    discount: 0,
    total: 1784.99,
    paidAmount: 1000,
    balance: 784.99,
    status: 'partial',
    paymentMethod: 'Credit',
    notes: 'Awaiting final payment.',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 15)),
    createdBy: 'user-1',
    createdByName: 'Admin User',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)),
    updatedAt: new Date(),
  },
  {
    id: 'inv-2',
    invoiceNumber: 'FAC-2024-0002',
    customerId: 'cust-2',
    customerName: 'Ben Carter',
    items: [
      {
        productId: 'prod-2',
        productName: 'Ergo-Flow Mechanical Keyboard',
        quantity: 2,
        unitPrice: 179.99,
        subtotal: 359.98,
      },
      {
        productId: 'prod-3',
        productName: 'Aura-Glow Smart Lamp',
        quantity: 1,
        unitPrice: 89.99,
        subtotal: 89.99,
      },
    ],
    subtotal: 449.97,
    tax: 85.49,
    discount: 25.0,
    total: 510.46,
    paidAmount: 510.46,
    balance: 0,
    status: 'paid',
    paymentMethod: 'Card',
    notes: '',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 5)),
    createdBy: 'user-1',
    createdByName: 'Admin User',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)),
    updatedAt: new Date(),
  },
  {
    id: 'inv-3',
    invoiceNumber: 'FAC-2024-0003',
    customerId: 'cust-3',
    customerName: 'Aisha Khan',
    items: [
      {
        productId: 'prod-5',
        productName: 'Zenith VR Headset',
        quantity: 1,
        unitPrice: 499.99,
        subtotal: 499.99,
      },
    ],
    subtotal: 499.99,
    tax: 95.0,
    discount: 0,
    total: 594.99,
    paidAmount: 0,
    balance: 594.99,
    status: 'pending',
    paymentMethod: 'Credit',
    notes: 'Due in 30 days.',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 30)),
    createdBy: 'user-1',
    createdByName: 'Admin User',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)),
    updatedAt: new Date(),
  },
    {
    id: 'inv-4',
    invoiceNumber: 'FAC-2024-0004',
    customerId: 'cust-1',
    customerName: 'Elena Rodriguez',
    items: [
       {
        productId: 'prod-2',
        productName: 'Ergo-Flow Mechanical Keyboard',
        quantity: 2,
        unitPrice: 179.99,
        subtotal: 359.98,
      },
    ],
    subtotal: 359.98,
    tax: 68.40,
    discount: 0,
    total: 428.38,
    paidAmount: 0,
    balance: 428.38,
    status: 'pending',
    paymentMethod: 'Credit',
    notes: '',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 25)),
    createdBy: 'user-1',
    createdByName: 'Admin User',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
    updatedAt: new Date(),
  },
];
