import type { Product, Invoice, Customer, User, Expense, Payment } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@nexusstore.com',
    displayName: 'Usuario Administrador',
    role: 'admin',
    photoURL: 'https://i.pravatar.cc/150?u=admin@nexusstore.com',
    isActive: true,
    createdAt: new Date(),
    lastLogin: new Date(),
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Arroz Diana 1kg',
    description: 'Arroz blanco de grano largo, ideal para el día a día.',
    sku: 'NEX-ARZ-001',
    barcode: '7702084000019',
    price: 4500,
    cost: 3200,
    taxRate: 0.05, // 5%
    stock: 80,
    minStock: 20,
    category: 'Granos',
    supplier: 'Distribuidora La Cosecha',
    imageUrl: 'https://picsum.photos/seed/NEX-ARZ-001/400/400',
    isActive: true,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-2',
    name: 'Azúcar Manuelita 1kg',
    description: 'Azúcar blanco refinado de alta pureza.',
    sku: 'NEX-AZU-002',
    barcode: '7702021000028',
    price: 3800,
    cost: 2800,
    taxRate: 0.19, // 19%
    stock: 8,
    minStock: 15,
    category: 'Endulzantes',
    supplier: 'Ingenio Manuelita',
    imageUrl: 'https://picsum.photos/seed/NEX-AZU-002/400/400',
    isActive: true,
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-3',
    name: 'Panela Pulverizada Doña Panela 500g',
    description: 'Panela 100% natural, sin aditivos.',
    sku: 'NEX-PAN-003',
    barcode: '7707205000034',
    price: 3200,
    cost: 2200,
    taxRate: 0, // 0%
    stock: 50,
    minStock: 20,
    category: 'Endulzantes',
    supplier: 'Trapiches del Valle',
    imageUrl: 'https://picsum.photos/seed/NEX-PAN-003/400/400',
    isActive: true,
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-4',
    name: 'Aceite Girasol 1L',
    description: 'Aceite vegetal para cocinar.',
    sku: 'NEX-ACE-004',
    barcode: '7702134000045',
    price: 12500,
    cost: 9500,
    taxRate: 0.19, // 19%
    stock: 120,
    minStock: 50,
    category: 'Aceites',
    supplier: 'Grasas y Aceites S.A.',
    imageUrl: 'https://picsum.photos/seed/NEX-ACE-004/400/400',
    isActive: true,
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date(),
  },
  {
    id: 'prod-5',
    name: 'Café Sello Rojo 500g',
    description: 'Café tostado y molido tradicional.',
    sku: 'NEX-CAF-005',
    barcode: '7702011000056',
    price: 18000,
    cost: 13500,
    taxRate: 0.19, // 19%
    stock: 4,
    minStock: 10,
    category: 'Bebidas',
    supplier: 'Colcafé',
    imageUrl: 'https://picsum.photos/seed/NEX-CAF-005/400/400',
    isActive: true,
    createdAt: new Date('2023-05-21'),
    updatedAt: new Date(),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Elena Rodríguez',
    email: 'elena.r@example.com',
    phone: '3001234567',
    address: 'Calle 100 # 19-54, Bogotá',
    taxId: '12345678-9',
    creditLimit: 5000000,
    currentBalance: 2149980,
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-2',
    name: 'Benjamín Carter',
    email: 'ben.c@example.com',
    phone: '3109876543',
    address: 'Carrera 43 # 75-30, Barranquilla',
    taxId: '98765432-1',
    creditLimit: 2000000,
    currentBalance: 0,
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-3',
    name: 'Aisha Khan',
    email: 'aisha.k@example.com',
    phone: '3205550103',
    address: 'Avenida El Poblado # 10-2, Medellín',
    taxId: '56473829-1',
    creditLimit: 10000000,
    currentBalance: 499990,
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date(),
  },
];

export let mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'FAC-2024-0001',
    customerId: 'cust-1',
    customerName: 'Elena Rodríguez',
    items: [
      {
        productId: 'prod-1',
        productName: 'Arroz Diana 1kg',
        quantity: 10,
        unitPrice: 4500,
        subtotal: 45000,
        taxRate: 0.05,
        taxAmount: 2250,
      },
    ],
    subtotal: 45000,
    tax: 2250,
    discount: 0,
    total: 47250,
    paidAmount: 20000,
    balance: 27250,
    status: 'partial',
    paymentMethod: 'Crédito',
    notes: 'Pago final pendiente.',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 15)),
    createdBy: 'user-1',
    createdByName: 'Usuario Administrador',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 10)),
    updatedAt: new Date(),
  },
  {
    id: 'inv-2',
    invoiceNumber: 'FAC-2024-0002',
    customerId: 'cust-2',
    customerName: 'Benjamín Carter',
    items: [
      {
        productId: 'prod-2',
        productName: 'Azúcar Manuelita 1kg',
        quantity: 5,
        unitPrice: 3800,
        subtotal: 19000,
        taxRate: 0.19,
        taxAmount: 3610,
      },
      {
        productId: 'prod-3',
        productName: 'Panela Pulverizada Doña Panela 500g',
        quantity: 3,
        unitPrice: 3200,
        subtotal: 9600,
        taxRate: 0,
        taxAmount: 0,
      },
    ],
    subtotal: 28600,
    tax: 3610,
    discount: 2000,
    total: 30210,
    paidAmount: 30210,
    balance: 0,
    status: 'paid',
    paymentMethod: 'Tarjeta',
    notes: '',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 5)),
    createdBy: 'user-1',
    createdByName: 'Usuario Administrador',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)),
    updatedAt: new Date(),
  },
  {
    id: 'inv-3',
    invoiceNumber: 'FAC-2024-0003',
    customerId: 'cust-3',
    customerName: 'Aisha Khan',
    items: [
      {
        productId: 'prod-5',
        productName: 'Café Sello Rojo 500g',
        quantity: 2,
        unitPrice: 18000,
        subtotal: 36000,
        taxRate: 0.19,
        taxAmount: 6840,
      },
    ],
    subtotal: 36000,
    tax: 6840,
    discount: 0,
    total: 42840,
    paidAmount: 0,
    balance: 42840,
    status: 'pending',
    paymentMethod: 'Crédito',
    notes: 'Vence en 30 días.',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 30)),
    createdBy: 'user-1',
    createdByName: 'Usuario Administrador',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)),
    updatedAt: new Date(),
  },
    {
    id: 'inv-4',
    invoiceNumber: 'FAC-2024-0004',
    customerId: 'cust-1',
    customerName: 'Elena Rodríguez',
    items: [
       {
        productId: 'prod-2',
        productName: 'Azúcar Manuelita 1kg',
        quantity: 20,
        unitPrice: 3800,
        subtotal: 76000,
        taxRate: 0.19,
        taxAmount: 14440,
      },
    ],
    subtotal: 76000,
    tax: 14440,
    discount: 0,
    total: 90440,
    paidAmount: 0,
    balance: 90440,
    status: 'pending',
    paymentMethod: 'Crédito',
    notes: '',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 25)),
    createdBy: 'user-1',
    createdByName: 'Usuario Administrador',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
    updatedAt: new Date(),
  },
];


export let mockPayments: Payment[] = [
    { 
        id: 'pay-1', 
        invoiceId: 'inv-1',
        invoiceNumber: 'FAC-2024-0001',
        amount: 20000, 
        paymentMethod: 'transfer', 
        reference: 'TXN-ABC-123',
        notes: 'Abono inicial.',
        createdBy: 'user-1',
        createdByName: 'Usuario Administrador',
        createdAt: new Date(new Date().setDate(new Date().getDate() - 9)) 
    },
];

export const mockExpenses: Expense[] = [
    {
      id: 'exp-1',
      date: new Date(new Date().setDate(new Date().getDate() - 15)),
      description: 'Pago de arriendo del local',
      category: 'Arriendo',
      amount: 1500000,
      createdBy: 'user-1',
    },
    {
      id: 'exp-2',
      date: new Date(new Date().setDate(new Date().getDate() - 5)),
      description: 'Factura de servicios públicos (Agua, Luz)',
      category: 'Servicios Públicos',
      amount: 350000,
      createdBy: 'user-1',
    },
    {
      id: 'exp-3',
      date: new Date(new Date().setDate(new Date().getDate() - 2)),
      description: 'Compra de papelería para la oficina',
      category: 'Suministros de Oficina',
      amount: 120000,
      createdBy: 'user-1',
    },
    {
      id: 'exp-4',
      date: new Date(new Date().setDate(new Date().getDate() - 1)),
      description: 'Pago de nómina primera quincena',
      category: 'Nómina',
      amount: 2500000,
      createdBy: 'user-1',
    },
  ];
